
services:
  db:
    build: 
      context: .
      dockerfile: PostgresDockerfile
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - Ecommerce_network

  web:
    build: .
    volumes:
      - ../E-commerce API:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - ./Ecommerce_API/.env
    networks:
      - Ecommerce_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health-check/"]
      interval: 120s
      timeout: 5s
      retries: 5

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    volumes:
      - ./ngrok_config/ngrok.yml:/ngrok.yml
    environment:
      - NGROK_AUTHTOKEN=2n4ONsudYEep1MocZoSdUrdWXwH_7n3kEV89tj5mzo6ySUVzJ
    command:
      - "start"
      - "--all"
      - "--config"
      - "/ngrok.yml"
    ports:
      - "4040:4040" # Ngrok dashboard
    depends_on:
      web:
        condition: service_healthy
    networks:
      - Ecommerce_network

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    networks:
      - Ecommerce_network

  celery_worker:
    build:
      context: .
      dockerfile: CeleryDockerfile
    # command: celery -A Ecommerce_API.Ecommerce_API worker --loglevel=debug
    volumes:
      - .:/app
    env_file:
      - ./Ecommerce_API/.env
    # environment:
      # DJANGO_SETTINGS_MODULE: Ecommerce_API.Ecommerce_API.settings
    depends_on:
      - redis
    networks:
      - Ecommerce_network


networks:
  Ecommerce_network:
    driver: bridge
    name: Ecommerce_network
    external: true