# Generated by Django 5.0 on 2024-10-13 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_unique_together_cart_product_variant_and_more'),
        ('products', '0008_colors_sizes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product_variant')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
    ]
