# Generated by Django 5.0 on 2024-12-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_discount_price_alter_cart_total_price_and_more'),
        ('coupons', '0003_alter_couponproduct_coupon_alter_couponuse_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartcoupon', to='coupons.coupon'),
        ),
    ]
