# Generated by Django 5.0 on 2024-12-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cartitem_product_variant'),
        ('products', '0011_colors_created_at_colors_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='products.productvariant'),
        ),
    ]
