# Generated by Django 5.0 on 2024-12-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cartitem_product_variant_alter_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartcoupon', to='cart.cart'),
        ),
    ]
