# Generated by Django 5.0 on 2024-12-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_cartcoupon_user'),
        ('coupons', '0004_alter_couponproduct_coupon'),
        ('products', '0011_colors_created_at_colors_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartcoupon',
            old_name='user',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='cart',
        ),
        migrations.AlterUniqueTogether(
            name='cartcoupon',
            unique_together={('cart', 'coupon')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_variant')},
        ),
    ]
