# Generated by Django 5.0 on 2024-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default=12341224543, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
