# Generated by Django 5.0 on 2024-09-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_date_orders_created_at_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ordersitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_items', to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='ordersitems',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
