# Generated by Django 5.0 on 2024-10-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordersitems_price_alter_orders_total_price_and_more'),
        ('products', '0005_remove_product_image_remove_product_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paymob_response',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='color',
            field=models.SmallIntegerField(choices=[(1, 'Red'), (2, 'Blue'), (3, 'Green'), (4, 'Yellow'), (5, 'Black'), (6, 'White'), (7, 'Orange'), (8, 'Purple')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='description',
            field=models.TextField(default='not provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='name',
            field=models.CharField(default='not provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersitems',
            name='size',
            field=models.SmallIntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large'), (3, 'XLarge'), (4, 'XXLarge'), (5, 'XXXLarge')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ordersitems',
            unique_together={('order', 'product_variant')},
        ),
    ]
