# Generated by Django 5.0 on 2024-10-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordersitems_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersitems',
            name='product',
        ),
    ]
