# Generated by Django 5.0 on 2024-10-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_user_alter_ordersitems_product_variant_and_more'),
        ('products', '0008_colors_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitems',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.colors'),
        ),
        migrations.AlterField(
            model_name='ordersitems',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.sizes'),
        ),
    ]
