# Generated by Django 5.0 on 2024-10-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_ordersitems_color_alter_ordersitems_size'),
        ('users', '0007_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
    ]
