# Generated by Django 5.0 on 2024-11-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Preparing your order'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Returned'), (5, 'Cancelled')], default=0),
        ),
    ]
