# Generated by Django 5.0 on 2024-11-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitems',
            name='image_url',
            field=models.URLField(default='media/1_21462672-d417-48dd-bf6a-f30be4ec3eca.jpeg'),
            preserve_default=False,
        ),
    ]
