# Generated by Django 5.0 on 2024-11-28 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '__first__'),
        ('orders', '0013_ordersitems_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_orders', to='coupons.coupons')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_coupons', to='orders.orders')),
            ],
            options={
                'unique_together': {('order', 'coupon')},
            },
        ),
    ]
