# Generated by Django 5.0 on 2024-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orders_discount_price_ordersitems_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_link',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Preparing your order'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Returned'), (5, 'Cancelled'), (6, 'Payment Failed')], default=0),
        ),
    ]
