# Generated by Django 5.0 on 2025-01-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orders_shipping_price_returnrequest_returnitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='paymob_response',
            field=models.JSONField(null=True),
        ),
    ]
