# Generated by Django 5.0 on 2025-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_returnrequest_paymob_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
