# Generated by Django 5.0 on 2025-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_returnitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
