# Generated by Django 5.0 on 2024-12-06 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0014_ordercoupons'),
        ('products', '0011_colors_created_at_colors_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupon',
        ),
        migrations.RenameModel(
            old_name='CouponProducts',
            new_name='CouponProduct',
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['seller', 'code'], name='coupons_cou_seller__1eacf4_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active'], name='coupons_cou_code_1aa9c7_idx'),
        ),
    ]
