# Generated by Django 5.0 on 2024-12-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_coupons_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponproduct',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couponproducts', to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='couponuse',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couponuse', to='coupons.coupon'),
        ),
    ]
