# Generated by Django 5.0 on 2024-12-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_couponproduct_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponrule',
            old_name='rule_value',
            new_name='minimum_required_value',
        ),
        migrations.RemoveField(
            model_name='couponrule',
            name='rule_type',
        ),
    ]
