# Generated by Django 5.0 on 2024-09-26 21:40

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='visible_in_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller_id', 'id'], name='products_pr_seller__16ce39_idx'),
        ),
    ]
