# Generated by Django 5.0 on 2024-10-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_url_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='visible_in_search',
        ),
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.SmallIntegerField(choices=[(1, 'Red'), (2, 'Blue'), (3, 'Green'), (4, 'Yellow'), (5, 'Black'), (6, 'White'), (7, 'Orange'), (8, 'Purple')])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'Product_Variant',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productvariant')),
            ],
            options={
                'db_table': 'Product_Images',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('price', models.FloatField()),
                ('size', models.SmallIntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large'), (3, 'XLarge'), (4, 'XXLarge'), (5, 'XXXLarge')])),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
            options={
                'db_table': 'Product_Variant_Sizes',
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('parent', 'id'), name='unique_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('color', 'id'), name='unique_color'),
        ),
        migrations.AddIndex(
            model_name='productimages',
            index=models.Index(fields=['product_id'], name='Product_Ima_product_ed870f_idx'),
        ),
        migrations.AddIndex(
            model_name='productimages',
            index=models.Index(fields=['product_variant_id'], name='Product_Ima_product_b9fcdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimages',
            constraint=models.UniqueConstraint(fields=('product_variant_id', 'url'), name='unique_product_variant_image'),
        ),
        migrations.AddConstraint(
            model_name='productvariantsizes',
            constraint=models.UniqueConstraint(fields=('product_variant', 'size'), name='unique_product_variant_size'),
        ),
    ]
