# Generated by Django 5.0 on 2024-10-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimages',
            name='unique_product_variant_image',
        ),
        migrations.RemoveIndex(
            model_name='productimages',
            name='Product_Ima_product_ed870f_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimages',
            name='Product_Ima_product_b9fcdc_idx',
        ),
        migrations.AddField(
            model_name='productimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-04 00:29:00.000000'),

            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimages',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='productimages',
            index=models.Index(fields=['product_id', 'in_use'], name='Product_Ima_product_254b32_idx'),
        ),
        migrations.AddIndex(
            model_name='productimages',
            index=models.Index(fields=['product_variant', 'created_at'], name='Product_Ima_product_4f5d28_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimages',
            constraint=models.UniqueConstraint(fields=('product_variant_id', 'in_use', 'url'), name='unique_product_variant_image'),
        ),
    ]
