# Generated by Django 5.0 on 2024-10-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimages_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Sizes',
            },
        ),
        migrations.RemoveField(
            model_name='productvariantsizes',
            name='product_variant',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_product_variant',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_color',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.colors'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.sizes'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['parent', 'id'], name='unique_product_variant'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['color', 'size', 'id'], name='unique_color_size'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['size', 'color', 'id'], name='unique_size_color'),
        ),
        migrations.DeleteModel(
            name='ProductVariantSizes',
        ),
    ]
