# Generated by Django 5.0 on 2024-10-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_colors_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productimages',
            name='Product_Ima_product_4f5d28_idx',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='productimages',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colors'),
        ),
        migrations.AddIndex(
            model_name='productimages',
            index=models.Index(fields=['product_id', 'color', 'created_at'], name='Product_Ima_product_421f62_idx'),
        ),
    ]
