# Generated by Django 5.0 on 2024-10-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productimages_product_ima_product_4f5d28_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='productimages',
            constraint=models.UniqueConstraint(fields=('product_id', 'url'), name='unique_product_variant_image'),
        ),
    ]
