# Generated by Django 5.0 on 2024-10-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_balance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_merchant_id',
        ),
    ]
