
## Rule Types
RULE_TYPE_MIN_PRODUCT_PRICE = 0
RULE_TYPE_MIN_ORDER_TOTAL_PRICE = 1

## Discount Types
DISCOUNT_TYPE_PERCENTAGE = 0
DISCOUNT_TYPE_FIXED = 1

## Coupon Types
COUPON_TYPE_ORDER = 0
COUPON_TYPE_PRODUCT = 1
COUPON_TYPE_SELLER = 2
COUPON_TYPE_SHIPPING = 3

PAYMENT_EXPIRY = 1 * 60

## Order Status
ORDER_PENDING = 0
ORDER_PAID = 1
ORDER_SHIPPED = 2
ORDER_DELIVERED = 3
ORDER_RETURNED = 4
ORDER_CANCELLED = 5
ORDER_FAILED = 6

## Return Status
RETURN_WAITING_FOR_SHIPPING = 0
RETURN_SHIPPING_BACK = 1
RETURN_CHECKING_PACKAGE = 2
RETURN_APPROVED = 3
RETURN_REJECTED = 4
RETURN_SHIPPED = 5
RETURN_CLOSED = 6