
## Rule Types
RULE_TYPE_MIN_PRODUCT_PRICE = 0
RULE_TYPE_MIN_ORDER_TOTAL_PRICE = 1

## Discount Types
DISCOUNT_TYPE_PERCENTAGE = 0
DISCOUNT_TYPE_FIXED = 1

## Coupon Types
COUPON_TYPE_ORDER = 0
COUPON_TYPE_PRODUCT = 1
COUPON_TYPE_SELLER = 2
COUPON_TYPE_SHIPPING = 3

PAYMENT_EXPIRY = 1 * 60